spring:
  profiles:
    active: prod

  data:
    rest:
      base-path: /api

  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB

  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000

server:
  port: 8081

support:
  email: duclmdev@gmail.com

---
spring:
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: USERNAME@gmail.com
    password: PASSWORD
    properties:
      mail:
        transport:
          protocol: smtps
        smtps:
          auth: true
          starttls:
            enable: true
            timeout: 8000
---
spring:
  profiles: test
conf:
  name: test-YAML
  environment: test
  servers:
    - www.abc.test.com
    - www.xyz.test.com

---
spring:
  profiles: prod
conf:
  name: prod-YAML
  environment: production
  servers:
    - www.abc.com
    - www.xyz.com
