/* Generated By:JavaCC: Do not edit this line. ExampleCompilerTreeConstants.java Version 6.0_beta */
package vn.elite.fundamental.parser.javacc;

public interface ExampleCompilerTreeConstants {
    int JJTCOMPILATIONUNIT = 0;
    int JJTVARDECLARE = 1;
    int JJTVOID = 2;
    int JJTASSIGNMENT = 3;
    int JJTORNODE = 4;
    int JJTANDNODE = 5;
    int JJTXORNODE = 6;
    int JJTEQNODE = 7;
    int JJTNEQNODE = 8;
    int JJTLTNODE = 9;
    int JJTGTNODE = 10;
    int JJTLENODE = 11;
    int JJTGENODE = 12;
    int JJTADDNODE = 13;
    int JJTMINUSNODE = 14;
    int JJTMULNODE = 15;
    int JJTDIVNODE = 16;
    int JJTMODNODE = 17;
    int JJTNOTNODE = 18;
    int JJTUNARYMINUSNODE = 19;
    int JJTIDENTIFIER = 20;
    int JJTSTRINGLITERAL = 21;
    int JJTINTLITERAL = 22;
    int JJTTRUE = 23;
    int JJTFALSE = 24;
    int JJTBLOCK = 25;
    int JJTIF = 26;
    int JJTWHILE = 27;
    int JJTPRINT = 28;

    String[] jjtNodeName = {
        "CompilationUnit",
        "VarDeclare",
        "void",
        "Assignment",
        "OrNode",
        "AndNode",
        "XorNode",
        "EQNode",
        "NEQNode",
        "LTNode",
        "GTNode",
        "LENode",
        "GENode",
        "AddNode",
        "MinusNode",
        "MulNode",
        "DivNode",
        "ModNode",
        "NotNode",
        "UnaryMinusNode",
        "Identifier",
        "StringLiteral",
        "IntLiteral",
        "True",
        "False",
        "Block",
        "If",
        "While",
        "Print",
    };
}
/* JavaCC - OriginalChecksum=0138ebfa58754822fc5ca2f1616aa7f5 (do not edit this line) */
