/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2019-12-03 09:33:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import edu.fpt.comp1640.model.user.User;
import edu.fpt.comp1640.model.user.Administrator;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/template/sidebar.jsp", Long.valueOf(1574060374399L));
    _jspx_dependants.put("/template/navbar.jsp", Long.valueOf(1574063533439L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("edu.fpt.comp1640.model.user.Administrator");
    _jspx_imports_classes.add("edu.fpt.comp1640.model.user.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    Object _user = session.getAttribute("user");
    if (_user == null) {
        response.sendRedirect(request.getContextPath() + "/index.jsp");
        return;
    }
    User user = (User) _user;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\"/>\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"./img/apple-icon.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"./img/favicon.ico\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\"/>\r\n");
      out.write("    <title>Dashboard</title>\r\n");
      out.write("    <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700,200\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/light-bootstrap-dashboard.css?v=2.0.1\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/demo.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<div class=\"sidebar\" data-color=\"orange\" data-image=\"./assets/img/university-of-greenwich.jpg\">\r\n");
      out.write("    <div class=\"sidebar-wrapper\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <a href=\"#\" class=\"simple-text logo-mini\">AM</a>\r\n");
      out.write("            <a href=\"#\" class=\"simple-text logo-normal\">Annual Magazine</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"user\">\r\n");
      out.write("            <div class=\"photo\">\r\n");
      out.write("                <img src=\"../img/default-avatar.png\"/>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"info \">\r\n");
      out.write("                <a data-toggle=\"collapse\" href=\"#collapseExample\" class=\"collapsed\">\r\n");
      out.write("                    <span>");
      out.print( user == null ? "" : user.getName() );
      out.write("<b class=\"caret\"></b></span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"collapse\" id=\"collapseExample\">\r\n");
      out.write("                    <ul class=\"nav\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"profile-dropdown\" href=\"#pablo\">\r\n");
      out.write("                                <span class=\"sidebar-mini\">MP</span>\r\n");
      out.write("                                <span class=\"sidebar-normal\">My Profile</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"profile-dropdown\" href=\"#pablo\">\r\n");
      out.write("                                <span class=\"sidebar-mini\">EP</span>\r\n");
      out.write("                                <span class=\"sidebar-normal\">Edit Profile</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"profile-dropdown\" href=\"#pablo\">\r\n");
      out.write("                                <span class=\"sidebar-mini\">S</span>\r\n");
      out.write("                                <span class=\"sidebar-normal\">Settings</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"nav\">\r\n");
      out.write("            <li class=\"nav-item \">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard.jsp\">\r\n");
      out.write("                    <i class=\"nc-icon nc-chart-pie-35\"></i>\r\n");
      out.write("                    <p>Dashboard</p>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 if (user.canSubmit()) {
      out.write("\r\n");
      out.write("            <li class=\"nav-item \">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/upload.jsp\">\r\n");
      out.write("                    <i class=\"nc-icon nc-simple-add\"></i>\r\n");
      out.write("                    <p> New Submission</p>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");
 if (user.canViewSubmission()) {
      out.write("\r\n");
      out.write("            <li class=\"nav-item \">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/submissions.jsp\">\r\n");
      out.write("                    <i class=\"nc-icon nc-bullet-list-67\"></i>\r\n");
      out.write("                    <p> Submissions</p>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");
 if (user.canViewStatistic()) {
      out.write("\r\n");
      out.write("            <li class=\"nav-item \">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statistic.jsp\">\r\n");
      out.write("                    <i class=\"nc-icon nc-chart\"></i>\r\n");
      out.write("                    <p> Statistic</p>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");
 if (user instanceof Administrator) {
      out.write("\r\n");
      out.write("            <li class=\"nav-item \">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/event.jsp\">\r\n");
      out.write("                    <i class=\"nc-icon nc-settings-gear-64\"></i>\r\n");
      out.write("                    <p> System Settings</p>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main-panel\">\r\n");
      out.write("        ");
      out.write("<nav class=\"navbar navbar-expand-lg \">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-wrapper\">\r\n");
      out.write("            <div class=\"navbar-minimize\">\r\n");
      out.write("                <button id=\"minimizeSidebar\" class=\"btn btn-warning btn-fill btn-round btn-icon d-none d-lg-block\">\r\n");
      out.write("                    <i class=\"fa fa-ellipsis-v visible-on-sidebar-regular\"></i>\r\n");
      out.write("                    <i class=\"fa fa-navicon visible-on-sidebar-mini\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("                aria-controls=\"navigation-index\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-bar burger-lines\"></span>\r\n");
      out.write("            <span class=\"navbar-toggler-bar burger-lines\"></span>\r\n");
      out.write("            <span class=\"navbar-toggler-bar burger-lines\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse justify-content-end\">\r\n");
      out.write("            <ul class=\"navbar-nav\">\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"http://example.com\" id=\"navbarDropdownMenuLink\"\r\n");
      out.write("                       data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                        <i class=\"nc-icon nc-bullet-list-67\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"dropdown-item text-danger\">\r\n");
      out.write("                            <i class=\"nc-icon nc-button-power\"></i> Log out\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-6 col-sm-6\">\r\n");
      out.write("                        <div class=\"card card-stats\">\r\n");
      out.write("                            <div class=\"card-body \">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-5\">\r\n");
      out.write("                                        <div class=\"icon-big text-center icon-warning\">\r\n");
      out.write("                                            <i class=\"nc-icon nc-send text-warning\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-7\">\r\n");
      out.write("                                        <div class=\"numbers\">\r\n");
      out.write("                                            <p class=\"card-category\">Submitted</p>\r\n");
      out.write("                                            <h4 class=\"card-title\"><span id=\"submitted\"></span> article(s)</h4>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-footer \">\r\n");
      out.write("                                <hr>\r\n");
      out.write("                                <div class=\"stats\"><i class=\"fa fa-refresh\"></i>Update Now</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6 col-sm-6\">\r\n");
      out.write("                        <div class=\"card card-stats\">\r\n");
      out.write("                            <div class=\"card-body \">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-5\">\r\n");
      out.write("                                        <div class=\"icon-big text-center icon-warning\">\r\n");
      out.write("                                            <i class=\"nc-icon nc-check-2 text-success\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-7\">\r\n");
      out.write("                                        <div class=\"numbers\">\r\n");
      out.write("                                            <p class=\"card-category\">Selected for publishing</p>\r\n");
      out.write("                                            <h4 class=\"card-title\"><span id=\"chosen\"></span> article(s)</h4>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-footer \">\r\n");
      out.write("                                <hr>\r\n");
      out.write("                                <div class=\"stats\"><i class=\"fa fa-refresh\"></i>Update Now</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6 col-sm-6\">\r\n");
      out.write("                        <div class=\"card card-stats\">\r\n");
      out.write("                            <div class=\"card-body \">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-5\">\r\n");
      out.write("                                        <div class=\"icon-big text-center icon-warning\">\r\n");
      out.write("                                            <i class=\"nc-icon nc-time-alarm text-danger\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-7\">\r\n");
      out.write("                                        <div class=\"numbers\">\r\n");
      out.write("                                            <p class=\"card-category\">Submission deadline</p>\r\n");
      out.write("                                            <h4 id=\"first_deadline\" class=\"card-title\">2019-04-30</h4>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-footer \">\r\n");
      out.write("                                <hr>\r\n");
      out.write("                                <div class=\"stats\">\r\n");
      out.write("                                    <i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("                                    <span class=\"py-name\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6 col-sm-6\">\r\n");
      out.write("                        <div class=\"card card-stats\">\r\n");
      out.write("                            <div class=\"card-body \">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-5\">\r\n");
      out.write("                                        <div class=\"icon-big text-center icon-warning\">\r\n");
      out.write("                                            <i class=\"nc-icon nc-planet text-primary\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-7\">\r\n");
      out.write("                                        <div class=\"numbers\">\r\n");
      out.write("                                            <p class=\"card-category\">Publishing deadline</p>\r\n");
      out.write("                                            <h4 id=\"second_deadline\" class=\"card-title\">2019-05-20</h4>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-footer \">\r\n");
      out.write("                                <hr>\r\n");
      out.write("                                <div class=\"stats\">\r\n");
      out.write("                                    <i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("                                    <span class=\"py-name\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/core/jquery.3.2.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/core/popper.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/core/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/plugins/bootstrap-switch.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/plugins/chartist.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/plugins/bootstrap-notify.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/plugins/jquery-jvectormap.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/plugins/moment.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/plugins/bootstrap-datetimepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/plugins/sweetalert2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/plugins/bootstrap-tagsinput.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/plugins/nouislider.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/plugins/bootstrap-selectpicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/plugins/jquery.validate.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/plugins/jquery.bootstrap-wizard.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/plugins/bootstrap-table.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/plugins/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/plugins/fullcalendar.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/light-bootstrap-dashboard.js?v=2.0.1\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/dashboard.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
